#!/bin/bash

n_jobs=$1

source ~/.bashrc
conda activate mrs

cd ..
bids_root=$PWD

rdas=($(ls -1 ./sub*/*/mrs/*.rda))

do_the_job() {
  rda=$1
  echo $rda
  out_dir=$(dirname $rda)
  spec2nii rda -j -o $out_dir $rda
}

export -f do_the_job

parallel -j $n_jobs do_the_job ::: "${rdas[@]}"
